### ISSUE TITLE
Unprocessable Entity returned for Search API calls

### ISSUE THREAD

**Issue by angusmack** [GnipDz/GnipForDotNet#1]
Great set of code by the way! 

I have been using your PowerTrack sample code in my own Azure Event Hub proxy without issue.

I now want to extend the Search API demo to allow me to back fill historical content from the last 30 days into Azure Event Hub, so I was looking at your demo code for this 'SearchDemo'.

Unfortunately even a simple search for "gnip" returns the dreaded 422 error.

Invalid HTTP Response code.BadRequest The remote server returned an error: (422) Unprocessable Entity. posted content = {"query":"gnip","fromDate":"201508101334","toDate":"201508111334","bucket":"day"}

To recreate simply clone repo, build solution and run the SearchDemo project.

I can curl the same search out on the command line and get results so most likely not to do with my account. We have migrated to v2.0 already.

Any help you give would be much appreciated.

**Comment by SnurfCo** [comment]
Hi,

Thanks!

Can you tell me if you have pulled code recently?  I made some changes to the code in the last couple weeks to support the 2.0 30 Day Search endpoint.  If you have not migrated yet, that is probably the cause.

**Comment by angusmack** [comment]
Yes, I did think about this. 

I was using an older pull and I started converting to the 2.0 endpoints for the search part as we have those endpoints enabled and are in migration. Then I checked the repo and saw your updates so I tried a totally fresh clone of the repo today to a new folder and got the same issue.

Maybe the fact that we are in migration is an issue? I'm not sure. We have both endpoints enabled but obviously v1 will drop off soon. What do you reckon? Is it something you can reproduce?

**Comment by angusmack** [comment]
Thinking about, as I mentioned in the first message,  I can query our 2.0 endpoints using curl and get the correct results so it won't be an account issue. Maybe I will try on a different machine.

**Comment by SnurfCo** [comment]
If this is for 30 day search, in the UI you should leave the checkboxes unchecked OR make sure the dates selected fall within the last 30 days.  Using the 30 Day search endpoint outside of the most recent 30 day window will result in a 422.

If you make any changes to the UI (like label or dates) you should hit the "clear" button before re-executing the Get Data/Get Counts commands as some objects are cached and reused unless cleared (perhaps not the best UI implementation, but I'm more of a server guy!)

**Comment by angusmack** [comment]
You know what, I think that might be it. What an idiot! I will confirm when back at desk and let you know. Thanks for your help with this.

**Comment by angusmack** [comment]
That was it! My sincere apologies. As we want to be able to search for set period of tweets and then send them to an Azure Event Hub I had the date ranges checked, but to something more than 30 days old. All sorted now.
